vich_uploader:
    db_driver: orm

    mappings:
        users_images:
            uri_prefix: /images/users_images
            upload_destination: '%kernel.project_dir%/public/images/users_images'
            namer: Vich\UploaderBundle\Naming\UniqidNamer
