# docker/docker-compose.yml
version: '3'

services:
  database:
    build:
      context: ./docker/database
    environment:
      - MYSQL_DATABASE=my_blog_db
      - MYSQL_USER=appuser
      - MYSQL_PASSWORD=apppassword
      - MYSQL_ROOT_PASSWORD=secret
    ports:
      - "3306:3306"
    volumes:
      - ./docker/database/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./docker/database/data:/var/lib/mysql

  php-fpm:
    build:
      context: ./docker/php-fpm
    links:
      - database
    depends_on:
      - database
    environment:
      - APP_ENV=dev
      - APP_SECRET=24e17c47430bd2044a61c131c1cf6990
      - DATABASE_URL=mysql://appuser:apppassword@database:3306/my_blog_db?serverVersion=mariadb-10.4.11
    volumes:
      - .:/var/www

  nginx:
    build:
      context: ./docker/nginx
    volumes:
      - .:/var/www
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/sites/:/etc/nginx/sites-available
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d
    depends_on:
      - php-fpm
    ports:
      - "80:80"
