controllers:
    resource: ../../src/Controller/
    type: annotation

kernel:
    resource: ../../src/Kernel.php
    type: annotation

#web_controller:
#    resource: ../../src/Infrastructure/Controller/Web/
#    type: annotation
#rest_controller:
#    resource: ../../src/Infrastructure/Controller/Rest/
#    type: annotation
#    prefix: /api
